# syntax=docker/dockerfile:1

## Build
FROM golang:1.20.2-buster AS build

WORKDIR /usr/src/app

COPY . .

RUN go mod download

RUN go build -o /docker-eligibility

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /docker-eligibility /docker-eligibility

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/docker-eligibility"]
